class VarHandler(object):
    var_dict = {
        "numeric_vars_zero_fill" : [
            # 'mortgage_-_amount_exact_',
            'mortgage',
            'visits',
            'cjm-currentphase',
            "samen_afsluiten_views",
            "zelf_afsluiten_views",
            "jouw_woonsituatie_views",
            "eerste_woning_views",
            "zelf_berekenen_views",
            "bestaande_woning_views",
            "volgende_woning_views",
            'finance_-_private_deposits',
            'finance_-_loan_payments_month',
            'loan_payments',
            "bestaande_woning_count",
            "volgende_woning_count",
            "starter_count"
    ],
    "numeric_vars_mean_fill" : [
        'currentscreenwidth',
        'visitclicks',
        'currentscreenheight',
        'clickcount',
        'frequency',
        'momentum',
        'recency',
         'intensity',
        'recent_intensity',
        'averagetime',
        'engagement_score',
        'loyalty_score',
        'prospect_score',
        'brand_prospect_score',
        # 'finance_-_annual_income',
        'annual_income',
        'age_partner',
        # 'finance_-_annual_income_partner',
        'annual_income_partner',
        'buy_price',
        'home_-_asking_price_exact_',
        'private_deposits',
        'plot_area',
        'surface',
        'contents',
        'built',
        'age',
        "time_to_calculator_use",
        'firstvisit',
        #'lastvisit',

    ],
    "categorical_vars_median" : [
        'language',
        'resolution',
        'currentbrowsername',
        'currentbrowserversion',
        'currentosversion',
        'devicetype',
        'currentosname',
        'browsername',
        'currentresolution',
        'browserversion',
        'osname',
        'osversion',
        'devicetypes',
        'testgroup',
        'sent_to_connection',
        'sent_to_system',
        'visiteddomain',
        'visitedchannel',
        'privacy_legislation',
        'entrypage',

        'referrerhost',
        'mr_geo_geoname_id',
        'geo_geoname_id',
        'referrerhosts',
        'mr_geo_country_name',
        'mr_geo_time_zone',
        'mr_geo_continent_code',
        'mr_geo_continent_name',
        'mr_geo_country_iso_code',
        # 'geo_time_zone',
        # 'geo_country_name',
        # 'geo_country_iso_code',
        # 'geo_continent_name',
        # 'geo_continent_code',
        'consented_objectives',
        'mr_geo_subdivision_1_iso_code',
        'mr_geo_subdivision_2_iso_code',
        'mr_geo_subdivision_2_name',
        'mr_geo_subdivision_1_name',
        'geo_city_name',
        'origin_source',
        'geo_subdivision_1_name',
        'geo_subdivision_2_name',
        'origin_type',
        'geo_subdivision_1_iso_code',
        'geo_subdivision_2_iso_code',
        'origin_detail',
        'mr_geo_latlong',
        'geo_latlong',
        'received_from_connection',
        'received_from_system',
        'engagement',
        'utm_medium',
        'utm_source',
        'Home-verzekering',
        'utm_campaign',
        'utm_content',
        'current_utm_source',
        'current_utm_campaign',
        'current_utm_medium',
        'visit_time',

        'current_utm_content',
        'permissionlevel',
        'marital_state',
        'permissionlevelset',
        'cookies_accepted',
        'visited_url_most_recent_',
        'prospect',
        'mortgage_type',
        'mortgage_provider',
        'interested_in',
        'campaigns_with_subsequent_action',
        'search_state',
        'bouw',
        'Brand-Vestigingnummer',
        'financial_obligations',
        'mortgage_type_interest',
        'pref_-_news_-_interesse',
        'property_build_plot',
        'brand_-_featured_button_click',
        'property_type',
        'utm_term',
        'situation_-_first_mariage',
        'bkr',
        'current_utm_term',
        'nationality',
        'home_have_in_mind',
        'loan_-_type_of_income',
        'int_-_product',
    ],
        "categorical_vars_none":
            [
                'refused_objectives',
                'afford',
                'appointment_reason',
                'currentkeywords',
                "Berekeningen",
                "visit_timestamps",
                #"soltest_-_rule_based",
                'mr_geo_city_name',
                'mr_geo_zipcode'

            ],
        "bool_datetimes" : [
            "calc_max_mortgage_allow_date",
            "cookies_accepted_date",
            "calc_monthly_costs_date",
            'search_state_date',
            'calc_afford_home_date',
            "AfspraakDatum",
            #"calc_visit_-_pakket_advies",
            'Brand-Vestigingnummer-date',
            'calc_home_value',
            'brand_-_afspraak_maken_visit_page_-_visit_date',
            'bkr_date',
            'calc_home_value_date',
            'brand_-_featured_button_click_-_date',
            'brand_-_rbs-id_-_date',
            'calc_visit_-_pakket_advies',
            'login_date',
            'propositiekiezer_-_visit_step_1',
            'home_have_in_mind_date',

        ],
        "occurence_counts" : [
            "calculator_used"
        ],
        "list_vars":
        [
            'url-name',
            'recentlyvieweditems',
            'keywords',
            "interactions_viewed",
            'visitedsites',
            'interactions_clicked',
            'interactions_converted',
        ]
    }

